site_name: Kafka Ease
site_description:  A library for the easy and automated creation of topics and acls in Kafka.
docs_dir: './docs/'
copyright: Copyright &copy; R. Domenzain 2023

repo_url: https://github.com/rdomenzain/kafka-ease
repo_name: kafka-ease

plugins:
    - search
    - glightbox
theme:
    name: material
    language: en
    icon:
        logo: octicons/tracked-by-closed-completed-24
        repo: fontawesome/brands/github
    font:
      text: Ubuntu
      code: Source Code Pro
    palette:
      # Palette toggle for light mode
      - media: "(prefers-color-scheme: light)"
        scheme: default
        primary: blue grey
        toggle:
          icon: material/weather-sunny
          name: Switch to dark mode
      # Palette toggle for dark mode
      - media: "(prefers-color-scheme: dark)"
        scheme: slate
        primary: black
        toggle:
          icon: material/weather-night
          name: Switch to light mode
    features:
        - navigation.tabs
        - navigation.sections
        - instant
        - content.code.copy
        - content.code.select

extra:
    manifest: "manifest.webmanifest"
    generator: false
    social:
        - icon: material/home
          link: https://rdomenzain.github.io/kafka-ease/
        - icon: material/github
          link: https://github.com/rdomenzain/kafka-ease

markdown_extensions:
    - toc:
          permalink: true
    - admonition
    - abbr
    - attr_list
    - codehilite
    - def_list
    - footnotes
    - md_in_html
    - meta
    - pymdownx.caret
    - pymdownx.critic
    - pymdownx.details
    - pymdownx.emoji:
          emoji_index: !!python/name:materialx.emoji.twemoji
          emoji_generator: !!python/name:materialx.emoji.to_svg
    - pymdownx.keys
    - pymdownx.snippets
    - pymdownx.superfences:
          custom_fences:
              - name: mermaid
                class: mermaid
                format: !!python/name:pymdownx.superfences.fence_code_format
    - pymdownx.tabbed
    - pymdownx.tasklist:
          custom_checkbox: true
    - pymdownx.tilde
    - pymdownx.highlight:
        anchor_linenums: true
        line_spans: __span
        pygments_lang_class: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences
